version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restify
